### ISSUE TITLE
ReferenceError: Element is not defined when using `Combobox`

### ISSUE THREAD

**Issue by yeminkhaung-airitech** [strapi/design-system#618]
### Required System information

- Npm version: 6.14.17
- NodeJS version: v14.19.3
- Strapi Design System version: 1.1.1
- Browser: Firefox 101.0
- React/React-DOM version: 18.1.0
- NextJS version: 10.0.6

### Describe the bug

I am using Next.js (React) and try to add starpi-design-system's `Combobox`. Error `ReferenceError: Element is not defined`  occurred when NextJS page is loaded (reference code below). `Box` component alone is working.

### Steps to reproduce the behavior

1. ComboBox is added according to documentation.
```
function HomePage {
  const [comboValue, setComboValue] = useState('');

  return (
      <>
        <Box padding={8} background="neutral100">
          <Combobox label="Food" value={comboValue} onChange={setComboValue}>
            <ComboboxOption value="hamburger">Hamburger</ComboboxOption>
            <ComboboxOption value="bagel">Bagel</ComboboxOption>
            <ComboboxOption value="tartuffo">Tartuffo</ComboboxOption>
            <ComboboxOption value="carbonara">Carbonara</ComboboxOption>
          </Combobox>
```
4. Start NextJS with `yarn dev`
5. load the page at localhost:3000
6. See error

### Full Error Log

```
yarn dev
yarn run v1.22.18
$ node server/server.js
Loaded env from /.env.local
info  - Using external babel configuration from /.babelrc
event - compiled successfully
> Ready on http://localhost:3000
event - build page: /404
wait  - compiling...
event - build page: /
event - build page: /
event - compiled successfully
ReferenceError: Element is not defined
    at eval (webpack-internal:///./src/Popover/Popover.js:180:75)
    at Module../src/Popover/Popover.js (\node_modules\@strapi\design-system\Combobox.development.js:598:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at eval (webpack-internal:///./src/Popover/index.js:2:66)
    at Module../src/Popover/index.js (\node_modules\@strapi\design-system\Combobox.development.js:610:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at eval (webpack-internal:///./src/Combobox/Combobox.js:24:67)
    at Module../src/Combobox/Combobox.js (\node_modules\@strapi\design-system\Combobox.development.js:370:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at eval (webpack-internal:///./src/Combobox/index.js:2:67)
    at Module../src/Combobox/index.js (\node_modules\@strapi\design-system\Combobox.development.js:418:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at \node_modules\@strapi\design-system\Combobox.development.js:94:18
    at \node_modules\@strapi\design-system\Combobox.development.js:97:10
    at webpackUniversalModuleDefinition (\node_modules\@strapi\design-system\Combobox.development.js:3:20)
    at Object.<anonymous> (\node_modules\@strapi\design-system\Combobox.development.js:10:3)
ReferenceError: Element is not defined
    at eval (webpack-internal:///./src/Popover/Popover.js:180:75)
    at Module../src/Popover/Popover.js (\node_modules\@strapi\design-system\Combobox.development.js:598:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at eval (webpack-internal:///./src/Popover/index.js:2:66)
    at Module../src/Popover/index.js (\node_modules\@strapi\design-system\Combobox.development.js:610:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at eval (webpack-internal:///./src/Combobox/Combobox.js:24:67)
    at Module../src/Combobox/Combobox.js (\node_modules\@strapi\design-system\Combobox.development.js:370:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at eval (webpack-internal:///./src/Combobox/index.js:2:67)
    at Module../src/Combobox/index.js (\node_modules\@strapi\design-system\Combobox.development.js:418:1)
    at __webpack_require__ (\node_modules\@strapi\design-system\Combobox.development.js:30:30)
    at \node_modules\@strapi\design-system\Combobox.development.js:94:18
    at \node_modules\@strapi\design-system\Combobox.development.js:97:10
    at webpackUniversalModuleDefinition (\node_modules\@strapi\design-system\Combobox.development.js:3:20)
    at Object.<anonymous> (\node_modules\@strapi\design-system\Combobox.development.js:10:3)
```

**Comment by HichamELBSI** [comment]
Hi @yeminkhaung-airitech,

Thanks for reporting the bug. Indeed, we are unfortunately using Element on proptypes and we shouldn't because Element is undefined on server side rendered apps.

I've made a fix here : https://github.com/strapi/design-system/pull/622
